# Generated by Django 5.0.6 on 2024-05-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tag_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='dashboard.tag', verbose_name='Теги'),
        ),
    ]
